// the to key is where the button on page takes you, not the navBar button
export const whoPage = {
 id: 'who-we-are',
 lightBg: true,
 lightText: false,
 lightTextDesc: false,
 topLine: 'Cine Suntem?',
 headline: 'O echipă de entuziaști ce iți sar in ajutor',
 description: [
  'Având contracte cu unele dintre cele mai mari service-uri , atât din Cluj cât și din Romania, echipa noatră garantează calitatea serviciilor oferite.',
 ],
 buttonLabel: 'Vezi ce facem',
 to: 'what-we-do',
 imgStart: false,
 img: require('../../images/photos/team.svg').default,
 alt: 'team',
 dark: false,
 darkText: true,
};
export const faqPage = {
 id: 'faq',
 lightBg: true,
 lightText: false,
 lightTextDesc: false,
 topLine: 'De ce să ne alegi pe noi?',
 headline: 'Întrebări adresate fregvent',
 description: [
  'Avănd contracte cu unele dintre cele mai mari service-uri , atăt din Cluj cât și din Romania, echipa noatră garantează calitatea serviciilor oferite',
 ],
 buttonLabel: 'Ce spun clienții',
 to: 'reviews',
 imgStart: false,
 img: require('../../images/photos/faq.svg').default,
 alt: 'faq',
 dark: false,
 darkText: true,
};
export const reviewPage = {
 id: 'reviews',
 lightBg: false,
 lightText: true,
 lightTextDesc: true,
 topLine: 'Încă nu te-ai hotărât?',
 headline: 'Uite ce spun clienții nostri',
 description: [
  '"Avănd contracte cu unele dintre cele mai mari service-uri , atăt din Cluj cât și din Romania, echipa noatră garantează calitatea serviciilor oferite"',
 ],
 buttonLabel: 'De ce noi?',
 to: 'whyUs',
 imgStart: true,
 img: require('../../images/photos/review.svg').default,
 alt: 'review-image',
 dark: true,
 darkText: false,
};
export const whyUsPage = {
 id: 'whyUs',
 lightBg: true,
 lightText: false,
 lightTextDesc: false,
 topLine: 'Nu te-ai convins?',
 headline: ' Iată ce avantaje ai dacă ne alegi pe noi să iți reparăm produsul',
 description: [
  '- Iți ridicăm aparatul defect chiar de la ușa ta. ',
  '-  Nu pierzi timp și bani căutând un service.',
  '- Nu pierzi timp pe drum până la service.',
  '- Iți garantăm reparația la cel mai bun service.',
  '- Garanție pe reparația facută 30 de zile.',
  '- Reparația efectuata cu noi include și transportul produsului defect.',
  '- Dacă costul reparației este mai mare decât valoarea aparatului, acesta va fi returnat la adresa de unde s-a ridicat fără nici un cost.',
  '- Ridicăm, repăram și returnăm in cel mai scurt timp.',
  '- Toate aparatele reparate vor fi curațate și optimizate pentru o funcționare corecta.',
  '- Recenziile de pe pagina noastră de facebook @wellfixit te vor convinge.',
 ],
 buttonLabel: 'Contactează-ne',
 to: 'contact',
 imgStart: false,
 img: require('../../images/photos/why-us.svg').default,
 alt: 'team',
 dark: false,
 darkText: true,
};
export const contactPage = {
 id: 'contact',
 lightBg: false,
 lightText: true,
 lightTextDesc: true,
 topLine: 'Ce mai aștepți?',
 headline: 'Contactează-ne',
 description: [
  'Program: ',
  'Luni-Vineri: 08:00-21:00',
  'Sâmbătă-Duminică: 08:00-18:00',
  'Tel: +4 0751 806 105',
  'Email: wellfixitcluj@yahoo.com',
 ],
 buttonLabel: 'Caută-ne pe Facebook',
 to: 'http://m.me/wellfixitcluj',
 imgStart: true,
 img: require('../../images/photos/contact.svg').default,
 alt: 'team',
 dark: true,
 darkText: false,
};
