export const whoPage = {
 id: 'who-we-are',
 lightBg: true,
 lightText: false,
 lightTextDesc: false,
 topLine: 'Cine Suntem?',
 headline: 'Un grup de entuziaști ce îți sar în ajutor',
 description: [
  'Avănd contracte cu unele dintre cele mai mari service-uri , atăt din Cluj cât și din Romania, echipa noatră garantează calitatea serviciilor oferite',
 ],
 buttonLabel: 'Vezi ce facem',
 to: 'what-we-do',
 imgStart: false,
 img: require('../../images/photos/team.svg').default,
 alt: 'team',
 dark: false,
 darkText: true,
};
export const faqPage = {
 id: 'faq',
 lightBg: true,
 lightText: false,
 lightTextDesc: false,
 topLine: 'De ce să ne alegi pe noi?',
 headline: 'Citește întrebările adresate fregvent',
 description: [
  'Avănd contracte cu unele dintre cele mai mari service-uri , atăt din Cluj cât și din Romania, echipa noatră garantează calitatea serviciilor oferite',
 ],
 buttonLabel: 'Ce spun clienții',
 to: 'reviews',
 imgStart: false,
 img: require('../../images/photos/faq.svg').default,
 alt: 'faq',
 dark: false,
 darkText: true,
};
export const reviewPage = {
 id: 'reviews',
 lightBg: false,
 lightText: true,
 lightTextDesc: true,
 topLine: 'Încă nu te-ai hotărât?',
 headline: 'Uite ce spun clienții nostri',
 description: [
  '"Avănd contracte cu unele dintre cele mai mari service-uri , atăt din Cluj cât și din Romania, echipa noatră garantează calitatea serviciilor oferite"',
 ],
 buttonLabel: 'Contactează-ne',
 to: 'contact',
 imgStart: true,
 img: require('../../images/photos/review.svg').default,
 alt: 'review-image',
 dark: true,
 darkText: false,
};

export const contactPage = {
 id: 'contact',
 lightBg: true,
 lightText: false,
 lightTextDesc: false,
 topLine: 'Ce mai aștepți?',
 headline: 'Contactează-ne',
 description: [
  'Program: ',
  'Luni-Sâmbătă: 09:00 -18:00',
  'Duminică: Indisponibil',
  'Tel: 0743934019',
  'Email: cevanume@emailprovider.extensie',
 ],
 buttonLabel: 'Caută-ne pe Facebook',
 to: 'http://fb.me/wellfixitcluj',
 imgStart: false,
 img: require('../../images/photos/contact.svg').default,
 alt: 'team',
 dark: false,
 darkText: true,
};
